baseURL = "https://counterflow.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Counterflow"
[markup.goldmark.renderer]
unsafe = true
